  GNU nano 2.5.3                                     File: config/secrets.yml                                                                       Modified  

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75508aa226d7e60b818a5296d8bfe9394b19557b207392504ee279210b442d729b1469d5429c75d515c88ef4934e3cf2b607556e2df47ef6f9009690ccc148f3

test:
  secret_key_base: 75508aa226d7e60b818a5296d8bfe9394b19557b207392504ee279210b442d729b1469d5429c75d515c88ef4934e3cf2b607556e2df47ef6f9009690ccc148f3

production:
  secret_key_base: 75508aa226d7e60b818a5296d8bfe9394b19557b207392504ee279210b442d729b1469d5429c75d515c88ef4934e3cf2b607556e2df47ef6f9009690ccc148f3

